title: Nuspell
description: > # this means to ignore newlines until next variable
  Nuspell is a fast and safe spelling checker software program. It is designed
  for languages with rich morphology and complex word compounding. Nuspell is
  written in modern C++ and it supports Hunspell dictionaries.
keywords: spelling checker spellcheck spellchecker spellchecking
#author: Nuspell community
#TODOemail: info@nuspell.org
#FIXMEurl: https://nuspell.org
url: "https://nuspell.github.io"

twitter_username: nuspell1
github_username:  nuspell
facebook_username: nuspell
#linkedin_username: nuspell
#pinterest_username: nuspell
#instagram_username: nuspell
mastodon:
 - username: nuspell
   instance: fosstodon.org

# Google Analytics
google_analytics: UA-122824583-1

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
