# Site settings
title: Nuspell
description: > # this means to ignore newlines until "baseurl:"
  Nuspell is a free and open source spell checker. It is written in C++ and
  extensively supports character encodings, locales, affixing, compounding and
  complex morphology. Nuspell offers also suggestions based on
  similarity, rules, pronunciation and personal dictionaries.
#TODOemail: info@nuspell.org
#FIXMEurl: https://nuspell.org
url: "https://nuspell.github.io"
twitter_username: nuspell1
github_username:  nuspell
facebook_username: nuspell
linkedin_username: nuspell
pinterest_username: nuspell
instagram_username: nuspell

# Build settings
markdown: kramdown

# Google Analytics
google_analytics: UA-122824583-1
